### ISSUE TITLE
We need a Han Solo mugshot (aka this is a test!)

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/.github#2]
# Description of problem

There is no Han Solo mugshot in this repo.

# Expected result

I expected a mugshot of Han Solo here.

# Actual result

No mugshot.

# Context

https://github.com/kata-containers/www.katacontainers.io/issues/18

**Comment by grahamwhaley** [comment]
Sadly, that might be copyright Lucas Arts of similar :-( ;-)
