### ISSUE TITLE
Don't require forward_labels for `kata-containers/kata-containers` repo nor for PRs targettng the `main` branch of the `kata-containers/tests` repo

### ISSUE THREAD

**Issue by fidencio** [kata-containers/.github#32]
Currently PRs going to `kata-containers/kata-containers` repo or to the `main`branch o the `kata-containers/tests` repo require forward_port labels.  However, they shouldn't as those are already the "main" development branches.

**Comment by dgibson** [comment]
Right, this is essentially a dupe of https://github.com/kata-containers/tests/issues/3180 but covering different repos.

**Comment by c3d** [comment]
We'd like to remove the need-review flag, but no can't do, no access. @kata-containers/action-admins, could I have access rights for this repo?

**Comment by jodh-intel** [comment]
@c3d - I've given the `kata-containers` group admin rights on this repo, which seems reasonable :smile:
