### ISSUE TITLE
Automation to move issues from `In Progress` to `Done` is not working

### ISSUE THREAD

**Issue by fidencio** [kata-containers/.github#35]
The https://github.com/orgs/kata-containers/projects/23 board has a `In Progress` column, which is not being automatically updated when the issues are closed.  This leaves the watcher with the (mistakenly) impression that we currently have hundreds of issues being worked on, while we only have a dozen of those.

There's the need to correctly reflect what we're working on in order to understand and prioritize better what we will want to work on in the future.

This was raised as part of the backlog scrub meeting.

/cc @ariel-adam @cpmeadors @cmaf @c3d @jodh-intel

**Comment by jodh-intel** [comment]
This is odd. The two GH actions we use are for:

- adding issues to the project ("").
  Still working - see https://github.com/kata-containers/kata-containers/issues/1927 which shows:
  > katacontainersbot added this to To do in Issue backlog 5 hours ago

- Moving them to "in progress" when they have an associated PR

  Still working - as an example see: https://github.com/kata-containers/kata-containers/issues/1926 which shows:
  > katacontainersbot moved this from To do to In progress in Issue backlog 27 minutes ago

And the GitHub-provided automation for the "Done" column (click the "..." top left of that column and select "Manage automation") correctly shows that issues should be moved to that column when closed... ?
