### ISSUE TITLE
add kata-env, if formatted well, to bug template

### ISSUE THREAD

**Issue by egernst** [kata-containers/.github#5]
**Which feature do you think can be improved?**

Our bug template should suggest adding in Kata environment info?

**How can it be improved?**

Usually when folks end up adding it, it is about 100000 lines of noise.

I really like how Alex pasted it for this issue: 
https://github.com/kata-containers/runtime/issues/1758

So, if we are to add it, I would recommend adding the formatting.

Even further, it may be useful to break down the kata-env results to include this .md formatting for us by 'section'

**Additional Information**

**Comment by grahamwhaley** [comment]
do you mean the output of `kata-collect-data`, or `kata-runtime kata-env` - just checking.
Does `kata-collect-data` not already include `kata-env` output.
Anyhow:
- yes, I like the indented attachement method. I've seen that more than once recently - did we make that a default now for some of the data capture @jodh-intel ?
- `kata-runtime kata-env` to generate markdown - I think that should not be hard and is potentially useful for bug reports, yes. iirc, I added the ability to output as json, and the code framework was already there, we just need to find a suitable markdown streamer for golang iirc.
