### ISSUE TITLE
moar labels: flakey-test and moar

### ISSUE THREAD

**Issue by egernst** [kata-containers/.github#7]
I think it'd be helpful to have a label along the lines of flakey-test to help identify problematic tests, and also PRs which are suffering from test flakes, perhaps?

Similarly, i'm lazy, and having a label area/kata-deploy would be nice too?

WDYT?

**Comment by grahamwhaley** [comment]
I'm not completely sold on either

- the flake label will by definition be attached to things that are flakey, and transitory. If the CI test is flakey, then it's not the PRs problem, it's a problem with the specific test - but then, you can't attach a label to a (bit of code relating to one) test. Best I can think of is you can open an Issue for the flake, link that Issue to the PRs where the flake has been seen, and put the label on the Issue.
- yeah, kata-deploy label is just you being lazy :-) We have to be careful about label explosion I think - we already have enough labels that it is pushing the limit of what my head will search through to find the one(s) I want..., and I don't think we should have labels for each sub-component of each repo. I can see that:
  - not all kata-deploy related items will land in the packaging repo (install issues will get reported in both docs and runtime for instance I suspect)
  - much though I'd like all kata-deploy items to have kata-deploy in the subject/title, as end-users may not realise it is a kata-deploy related issue, that is unlikely to happen either.
